# Generated by Django 4.1.1 on 2022-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('your_interest', models.CharField(choices=[('xray_technician', 'xray_technician'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=20)),
            ],
        ),
    ]
